# Default theme for Lubuntu by The Lubuntu Artwork Team:
# Rafael Laguna and Alexander Andjelkovic
# Based on Radiance. GPL2 / Open Source licensed
# More info at: https://launchpad.net/~lubuntu-art

[Desktop Entry]
Name=Box
Type=X-GNOME-Metatheme
Comment=Default Lubuntu theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Box
IconTheme=Box
CursorTheme=DMZ-Black
CursorSize=24
NotificationTheme=ubuntu
MetacityTheme=Box
ButtonLayout=close,minimize,maximize:
